name: Build and Push to Registry

on:
  push:
    branches: [ "dev", "preprod", "prod" ]
    paths:
      - 'demo-argocd/backend/**'
      - 'demo-argocd/frontend/**'
      - 'demo-argocd/k8s/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Backend
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }} ./backend
          docker push ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }}

      - name: Build & Push Frontend
        run: |
          docker build -t ghcr.io/${{ github.repository }}/frontend:${{ github.ref_name }} ./frontend
          docker push ghcr.io/${{ github.repository }}/frontend:${{ github.ref_name }}
