name: Terragrunt Infra Deployment

on:
  push:
    branches: [ "main", "dev", "preprod", "prod" ]
    paths:
      - 'environments/**'
      - 'modules/**'

jobs:
  terragrunt:
    name: Terragrunt Pipeline Run
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "ap-south-1"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Setup Terragrunt Binary
        uses: alpine-github-actions/terragrunt@v3
        with:
          terragrunt_version: "v0.55.0"

      # Dynamically navigates straight into your branch's directory (e.g., environments/dev)
      - name: Terragrunt Run All Components
        run: |
          cd environments/${{ github.ref_name }}
          terragrunt run-all init --terragrunt-non-interactive
          terragrunt run-all apply --terragrunt-non-interactive -auto-approve
